version: '2'
services:
  proxy:
    build:
        context: ./docker/proxynginx
        dockerfile: Dockerfile
    volumes:
      - letsencrypt_certs:/etc/nginx/certs
      - letsencrypt_www:/var/www/letsencrypt
    links:
      - app:impartialbot.sadsoft.com
    ports:
      - "80:80"
      - "443:443"
    restart: always
  letsencrypt:
    build:
      context: ./docker/letsencrypt
      dockerfile: Dockerfile
    command: /bin/true
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - letsencrypt_www:/var/www/letsencrypt
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
#   image: digi/app
#    ports:
#     - "8080:80"
    volumes:
     - .:/var/www/html
    networks:
     - digi
    restart: always
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        uid: "999"
#   image: digi/node
    user: node
    tty: true
    volumes:
      - .:/var/www/html
    networks:
      - digi
#  ngrok:
#    image: wernight/ngrok
#    links:
#      - app
#    ports:
#      - "4040:80"
#    volumes:
#      - .:/var/www/html
#    networks:
#      - digi
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "homestead"
      MYSQL_USER: "homestead"
      MYSQL_PASSWORD: "secret"
    volumes:
     - digimysql:/var/lib/mysql
     # - ./docker/mysql/conf.d:/etc/mysql/conf.d
     # - ./docker/mysql/logs:/var/log/mysql
    networks:
     - digi
  redis:
    image: redis:alpine
    volumes:
     - digiredis:/data
    networks:
     - digi
networks:
  digi:
    driver: "bridge"
volumes:
  letsencrypt_certs: ~
  letsencrypt_www: ~
  digimysql:
    driver: "local"
  digiredis:
    driver: "local"
